services:
  imgpage:
    image: timmijinks/img2article-frontend:latest
    build: ./imgpage
    ports:
      - "3000:3000"
    restart: always
  backendinator:
    image: timmijinks/img2article-backend:latest
    build: ./backendinator
    ports:
      - "8888:8888"
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wdygdtw
      - MONGO_INITDB_ROOT_PASSWORD=the_password_of_wdygdtw
    command: mongod --auth
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
