services:
  imgpage:
    image: timmijinks/img2article-frontend:latest
    build: ./imgpage
    ports:
      - "3000:3000"
    restart: always
  backendinator:
    image: timmijinks/img2article-backend:latest
    build: ./backendinator
    ports:
      - "8888:8888"
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    restart: always
