[package]
name = "wikipedia-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
quick-xml = { version = "0.37.1", features = ["serialize"] }
serde = { version = "1.0.215", features = ["derive"] }
